require("plugins.packer")
--PLUGINS--
require("nvim-tree").setup()
require("nvim-ts-autotag").setup()
require("gitsigns").setup()
require("bufferline").setup()
require("Comment").setup()

require("plugins.autopairs")
require("plugins.dashboard")
require("plugins.feline")
require("plugins.signature")
require("plugins.lsp-installer")
require("plugins.lspconfig").setup()
require("plugins.cmp")
require("plugins.treesitter")
require("plugins.null-ls")
